server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
    
  mvc:
    view:
      prefix: /templates/
      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    
    
  security:
    oauth2:
      client:
        registration:
          # Google
          google:
            client-id: 284851031585-60d3m4ic3kbhgek9hj13s8tluroa2vd1.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
            
          # Facebook
          facebook:
            client-id: 1356588308289840
            client-secret: 1dea7bde1988c4a55b740f6f77eec2b9
            scope:
            - email
            - public_profile
            
          # Naver
          naver:
            client-id: DU0NKKLnh8Rn3kfwRQ8Z
            client-secret: bRPo9_0TwA
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver # Provider 형식이 아니기 때문에 기입 해줘야함!
        
        # Provider ID must be specified for client registration 'naver'
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줍니다.
           